    private static void a(com.facebook.a.z)
    {
        java.lang.Throwable $r8;
        android.content.Context $r1;
        java.io.FileOutputStream $r4;
        java.lang.Exception $r5, $r9;
        java.io.File $r7;
        java.io.BufferedOutputStream $r3;
        com.facebook.a.z $r0;
        java.io.ObjectOutputStream $r2;
        java.lang.String $r6;

        $r0 := @parameter0: com.facebook.a.z;

        $r1 = staticinvoke <com.facebook.x: android.content.Context f()>();

     label01:
        $r2 = new java.io.ObjectOutputStream;

        $r3 = new java.io.BufferedOutputStream;

     label02:
        $r4 = virtualinvoke $r1.<android.content.Context: java.io.FileOutputStream openFileOutput(java.lang.String,int)>("AppEventsLogger.persistedevents", 0);

        specialinvoke $r3.<java.io.BufferedOutputStream: void <init>(java.io.OutputStream)>($r4);

        specialinvoke $r2.<java.io.ObjectOutputStream: void <init>(java.io.OutputStream)>($r3);

     label03:
        virtualinvoke $r2.<java.io.ObjectOutputStream: void writeObject(java.lang.Object)>($r0);

     label04:
        staticinvoke <com.facebook.internal.cb: void a(java.io.Closeable)>($r2);

        return;

     label05:
        $r5 := @caughtexception;

        $r2 = null;

     label06:
        $r6 = <com.facebook.a.m: java.lang.String a>;

        staticinvoke <android.util.Log: int w(java.lang.String,java.lang.String,java.lang.Throwable)>($r6, "Got unexpected exception while persisting events: ", $r5);

     label07:
        $r7 = virtualinvoke $r1.<android.content.Context: java.io.File getFileStreamPath(java.lang.String)>("AppEventsLogger.persistedevents");

        virtualinvoke $r7.<java.io.File: boolean delete()>();

     label08:
        staticinvoke <com.facebook.internal.cb: void a(java.io.Closeable)>($r2);

        return;

     label09:
        $r8 := @caughtexception;

        $r2 = null;

     label10:
        staticinvoke <com.facebook.internal.cb: void a(java.io.Closeable)>($r2);

        throw $r8;

     label11:
        $r8 := @caughtexception;

        goto label10;

     label12:
        $r9 := @caughtexception;

        goto label08;

     label13:
        $r5 := @caughtexception;

        goto label06;

        catch java.lang.Exception from label02 to label03 with label05;
        catch java.lang.Throwable from label01 to label03 with label09;
        catch java.lang.Exception from label03 to label04 with label13;
        catch java.lang.Throwable from label03 to label04 with label11;
        catch java.lang.Throwable from label06 to label07 with label11;
        catch java.lang.Exception from label07 to label08 with label12;
        catch java.lang.Throwable from label07 to label08 with label11;
    }
