    public final util.h.xy.ct.rb \u02cb(int)
    {
        java.lang.Throwable $r5;
        util.h.xy.ct.d r0;
        util.h.xy.ct.rb $r3;
        java.util.Vector $r1;
        byte $b3;
        int $i0, $i1, $i2;
        java.lang.Object $r2;
        java.lang.ArithmeticException $r4;

        r0 := @this: util.h.xy.ct.d;

        $i0 := @parameter0: int;

        $i1 = <util.h.xy.ct.d: int \u02cb>;

        $i1 = $i1 + 21;

        $i2 = $i1 % 128;

        <util.h.xy.ct.d: int \u141d> = $i2;

        $i1 = $i1 % 2;

        if $i1 != 0 goto label1;

        $b3 = 43;

        goto label2;

     label1:
        $b3 = 48;

     label2:
        if $b3 == 43 goto label3;

        $r1 = r0.<util.h.xy.ct.d: java.util.Vector \u02ca>;

        $r2 = virtualinvoke $r1.<java.util.Vector: java.lang.Object elementAt(int)>($i0);

        $r3 = (util.h.xy.ct.rb) $r2;

        return $r3;

     label3:
        $r1 = r0.<util.h.xy.ct.d: java.util.Vector \u02ca>;

        $r2 = virtualinvoke $r1.<java.util.Vector: java.lang.Object elementAt(int)>($i0);

        $r3 = (util.h.xy.ct.rb) $r2;

     label4:
        $r4 = new java.lang.ArithmeticException;

        specialinvoke $r4.<java.lang.ArithmeticException: void <init>()>();

        throw $r4;

     label5:
        $r5 := @caughtexception;

        throw $r5;

        catch java.lang.Throwable from label4 to label5 with label5;
    }
