    public final util.h.xy.cy.f \u02bc()
    {
        java.lang.Throwable $r2;
        util.h.xy.cy.ml r0;
        int $i0, $i1;
        java.lang.String $r3;
        util.h.xy.cy.g $r4;
        util.h.xy.cy.f $r1;

        r0 := @this: util.h.xy.cy.ml;

        $i0 = <util.h.xy.cy.ml: int \u02cb>;

        $i1 = $i0 | 69;

        $i1 = $i1 << 1;

        $i0 = $i0 ^ 69;

        $i0 = $i1 - $i0;

        $i0 = $i0 % 128;

        <util.h.xy.cy.ml: int \u02cf> = $i0;

     label1:
        $r1 = virtualinvoke r0.<util.h.xy.cy.ml: util.h.xy.cy.f \u02bd()>();

     label2:
        $i0 = <util.h.xy.cy.ml: int \u02cb>;

        $i0 = $i0 + 108;

        $i0 = $i0 + -1;

        $i1 = $i0 % 128;

        <util.h.xy.cy.ml: int \u02cf> = $i1;

        return $r1;

     label3:
        $r2 := @caughtexception;

        $r4 = new util.h.xy.cy.g;

        $r3 = virtualinvoke $r2.<java.lang.Throwable: java.lang.String getMessage()>();

        specialinvoke $r4.<util.h.xy.cy.g: void <init>(java.lang.String,java.lang.Throwable)>($r3, $r2);

        throw $r4;

        catch java.io.IOException from label1 to label2 with label3;
    }
