    void \u02ca(int, byte[]) throws java.io.IOException
    {
        java.lang.Throwable $r2;
        byte[] $r1;
        int $i0, $i1;
        java.lang.NullPointerException r3;
        util.h.xy.cy.mf r0;
        boolean $z0;

        r0 := @this: util.h.xy.cy.mf;

        $i0 := @parameter0: int;

        $r1 := @parameter1: byte[];

        $i1 = <util.h.xy.cy.mf: int \u02bb>;

        $i1 = $i1 + 105;

        $i1 = $i1 % 128;

        <util.h.xy.cy.mf: int \u02bc> = $i1;

        virtualinvoke r0.<util.h.xy.cy.mf: void \u02ce(int)>($i0);

        $i0 = lengthof $r1;

        virtualinvoke r0.<util.h.xy.cy.mf: void \u02ca(int)>($i0);

        virtualinvoke r0.<util.h.xy.cy.mf: void \u02ce(byte[])>($r1);

        $i0 = <util.h.xy.cy.mf: int \u02bb>;

        $i0 = $i0 + 103;

        $i1 = $i0 % 128;

        <util.h.xy.cy.mf: int \u02bc> = $i1;

        $i0 = $i0 % 2;

        if $i0 != 0 goto label1;

        $z0 = 1;

        goto label2;

     label1:
        $z0 = 0;

     label2:
        if $z0 == 1 goto label3;

        return;

     label3:
        r3 = new java.lang.NullPointerException;

        specialinvoke r3.<java.lang.NullPointerException: void <init>(java.lang.String)>("This statement would have triggered an Exception: specialinvoke $u2#13.<java.lang.Object: int hashCode()>()");

        throw r3;

     label4:
        $r2 := @caughtexception;

        throw $r2;

        catch java.lang.Throwable from label3 to label4 with label4;
    }
