    public final util.h.xy.cy.f \u02bc()
    {
        java.lang.Throwable $r2;
        int $i0, $i1;
        java.lang.String $r4;
        util.h.xy.cy.g $r3;
        util.h.xy.cy.f $r1;
        util.h.xy.cy.u r0;

        r0 := @this: util.h.xy.cy.u;

        $i0 = <util.h.xy.cy.u: int \u02ca>;

        $i1 = $i0 & 119;

        $i0 = $i0 | 119;

        $i1 = $i1 + $i0;

        $i1 = $i1 % 128;

        <util.h.xy.cy.u: int \u02ce> = $i1;

     label1:
        $r1 = virtualinvoke r0.<util.h.xy.cy.u: util.h.xy.cy.f \u02bd()>();

     label2:
        $i0 = <util.h.xy.cy.u: int \u02ce>;

        $i1 = $i0 ^ 15;

        $i0 = $i0 & 15;

        $i0 = $i0 << 1;

        $i1 = $i1 + $i0;

        $i0 = $i1 % 128;

        <util.h.xy.cy.u: int \u02ca> = $i0;

        return $r1;

     label3:
        $r2 := @caughtexception;

        $r3 = new util.h.xy.cy.g;

        $r4 = virtualinvoke $r2.<java.lang.Throwable: java.lang.String getMessage()>();

        specialinvoke $r3.<util.h.xy.cy.g: void <init>(java.lang.String,java.lang.Throwable)>($r4, $r2);

        throw $r3;

        catch java.io.IOException from label1 to label2 with label3;
    }
