    public final util.h.xy.ct.mf \u037a() throws java.io.IOException
    {
        java.lang.Throwable $r4;
        util.h.xy.ct.rg $r3;
        util.h.xy.ct.d $r1;
        util.h.xy.ct.m r0;
        java.lang.NullPointerException r5;
        util.h.xy.ct.k $r2;
        byte $b2;
        int $i0, $i1;

        r0 := @this: util.h.xy.ct.m;

        $r2 = new util.h.xy.ct.k;

        $r3 = r0.<util.h.xy.ct.m: util.h.xy.ct.rg \u02ce>;

        $r1 = virtualinvoke $r3.<util.h.xy.ct.rg: util.h.xy.ct.d \u02cb()>();

        specialinvoke $r2.<util.h.xy.ct.k: void <init>(util.h.xy.ct.d)>($r1);

        $i0 = <util.h.xy.ct.m: int \u02cf>;

        $i1 = $i0 | 77;

        $i1 = $i1 << 1;

        $i0 = $i0 ^ 77;

        $i0 = $i1 - $i0;

        $i1 = $i0 % 128;

        <util.h.xy.ct.m: int \u141d> = $i1;

        $i0 = $i0 % 2;

        if $i0 != 0 goto label1;

        $b2 = 85;

        goto label2;

     label1:
        $b2 = 13;

     label2:
        if $b2 == 85 goto label3;

        return $r2;

     label3:
        r5 = new java.lang.NullPointerException;

        specialinvoke r5.<java.lang.NullPointerException: void <init>(java.lang.String)>("This statement would have triggered an Exception: specialinvoke $u1#13.<java.lang.Object: int hashCode()>()");

        throw r5;

     label4:
        $r4 := @caughtexception;

        throw $r4;

        catch java.lang.Throwable from label3 to label4 with label4;
    }
