    public final util.h.xy.ct.mf \u02bb()
    {
        java.lang.Throwable $r3, $r4;
        util.h.xy.ct.rf $r5;
        util.h.xy.ct.mf $r1;
        util.h.xy.ct.ml r0;
        int $i0, $i1;
        java.lang.ArithmeticException $r2;
        java.lang.String $r6;
        boolean $z0;

        r0 := @this: util.h.xy.ct.ml;

        $i1 = <util.h.xy.ct.ml: int \u02cb>;

        $i0 = $i1 | 45;

        $i0 = $i0 << 1;

        $i1 = $i1 ^ 45;

        $i1 = $i0 - $i1;

        $i0 = $i1 % 128;

        <util.h.xy.ct.ml: int \u141d> = $i0;

        $i1 = $i1 % 2;

        if $i1 == 0 goto label01;

        $z0 = 0;

        goto label02;

     label01:
        $z0 = 1;

     label02:
        if $z0 == 0 goto label05;

     label03:
        $r1 = virtualinvoke r0.<util.h.xy.ct.ml: util.h.xy.ct.mf \u037a()>();

     label04:
        $i1 = <util.h.xy.ct.ml: int \u02cb>;

        $i0 = $i1 | 111;

        $i0 = $i0 << 1;

        $i1 = $i1 ^ 111;

        $i1 = $i0 - $i1;

        $i1 = $i1 % 128;

        <util.h.xy.ct.ml: int \u141d> = $i1;

        return $r1;

     label05:
        virtualinvoke r0.<util.h.xy.ct.ml: util.h.xy.ct.mf \u037a()>();

     label06:
        $r2 = new java.lang.ArithmeticException;

     label07:
        specialinvoke $r2.<java.lang.ArithmeticException: void <init>()>();

     label08:
        throw $r2;

     label09:
        $r3 := @caughtexception;

        throw $r3;

     label10:
        $r4 := @caughtexception;

        $r5 = new util.h.xy.ct.rf;

        $r6 = virtualinvoke $r4.<java.lang.Throwable: java.lang.String getMessage()>();

        specialinvoke $r5.<util.h.xy.ct.rf: void <init>(java.lang.String,java.lang.Throwable)>($r6, $r4);

        throw $r5;

        catch java.io.IOException from label03 to label04 with label10;
        catch java.io.IOException from label05 to label06 with label10;
        catch java.io.IOException from label07 to label08 with label10;
        catch java.lang.Throwable from label06 to label09 with label09;
    }
